
outData = [
			{
				"ozone": 20, 
				"nitrogen": 50, 
				"sulphur": 70, 
				"small": 5, 
				"large": 10, 
			},
			{
				"ozone": 50, 
				"nitrogen": 100, 
				"sulphur": 150, 
				"small": 20, 
				"large": 30, 
			},
			{
				"ozone": 90, 
				"nitrogen": 150, 
				"sulphur": 250, 
				"small": 30, 
				"large": 40, 
			},
			{
				"ozone": 130,
				"nitrogen": 250, 
				"sulphur": 350,
				"small": 45, 
				"large": 60, 
			},
			{
				"ozone": 150, 
				"nitrogen": 300, 
				"sulphur": 500, 
				"small": 55, 
				"large": 70, 
			},
			{
				"ozone": 170, 
				"nitrogen": 450, 
				"sulphur": 700, 
				"small": 50, 
				"large": 80, 
			},
			{
				"ozone": 200, 
				"nitrogen": 500, 
				"sulphur": 800, 
				"small": 60, 
				"large": 90, 
			},
			{
				"ozone": 220, 
				"nitrogen": 550, 
				"sulphur": 900, 
				"small": 65, 
				"large": 95, 
			},
			{
				"ozone": 300, 
				"nitrogen": 700, 
				"sulphur": 1100, 
				"small": 80, 
				"large": 110, 
			},
		]

simulatedData = [
					{
						"wind": 5,
						"rain": 4, 
						"condition": 950, 
						"humidityOutdoor": 30, 
						"humidityIndoor": 50, 
						"tempOutdoor": 5,
						"tempIndoor": 20,
						"aqiOutdoor": 1,
						"aqiIndoor": 2,
					},
					{
						"wind": 20,
						"rain": 0, 
						"condition": 970, 
						"humidityOutdoor": 30, 
						"humidityIndoor": 50, 
						"tempOutdoor": 5, 
						"tempIndoor": 20, 
						"aqiOutdoor": 4,
						"aqiIndoor": 7,
					},
					{
						"wind": 7,
						"rain": 10, 
						"condition": 930, 
						"humidityOutdoor": 30, 
						"humidityIndoor": 50, 
						"tempOutdoor": 5, 
						"tempIndoor": 20, 
						"aqiOutdoor": 2,
						"aqiIndoor": 3,
					},
					{
						"wind": 3,
						"rain": 1, 
						"condition": 1000, 
						"humidityOutdoor": 55, 
						"humidityIndoor": 39, 
						"tempOutdoor": 27,
						"tempIndoor": 23, 
						"aqiOutdoor": 1,
						"aqiIndoor": 2,
					},
					{
						"wind": 0,
						"rain": 3, 
						"condition": 1150, 
						"humidityOutdoor": 10, 
						"humidityIndoor": 35, 
						"tempOutdoor": -5,
						"tempIndoor": 25, 
						"aqiOutdoor": 3,
						"aqiIndoor": 4,
					},
					{
						"wind": 13,
						"rain": 1, 
						"condition": 999, 
						"humidityOutdoor": 50, 
						"humidityIndoor": 60, 
						"tempOutdoor": 13,
						"tempIndoor": 24,
						"aqiOutdoor": 5,
						"aqiIndoor": 2,
					},
					{
						"wind": 9,
						"rain": 4, 
						"condition": 1259, 
						"humidityOutdoor": 75, 
						"humidityIndoor": 60, 
						"tempOutdoor": 17,
						"tempIndoor": 21,
						"aqiOutdoor": 4,
						"aqiIndoor": 8,
					}

				]
